import type {
  ContractDefinition,
  ContractId,
  CyberwareDefinition,
  CyberwareId,
  FactionKey,
  WeaponUpgradeDefinition,
  WeaponUpgradeId,
} from './types';

export const DEFAULT_CONTRACT_ID: ContractId = 'morrow-relay';
export const DEFAULT_CYBERWARE_ID: CyberwareId = 'mesh';

export const FACTION_DETAILS: Record<FactionKey, {
  name: string;
  shortName: string;
  accent: string;
  description: string;
}> = {
  morrow: {
    name: 'Morrow Relay Co-op',
    shortName: 'Morrow',
    accent: '#4cefff',
    description: 'Courier unionists and route-fixers keeping the district from collapsing into silence.',
  },
  helix: {
    name: 'Helix Directorate',
    shortName: 'Helix',
    accent: '#ff8e74',
    description: 'Corporate retention teams, deniable armor, and the kind of cleanup crews that erase witnesses.',
  },
  glasshouse: {
    name: 'Glasshouse Combine',
    shortName: 'Glasshouse',
    accent: '#7af7b8',
    description: 'Broker syndicates, smugglers, and polished ghosts who buy neighborhoods one leverage point at a time.',
  },
};

export const CYBERWARE_OPTIONS: CyberwareDefinition[] = [
  {
    id: 'mesh',
    title: 'Subdermal Mesh',
    slotLabel: 'Core shell',
    summary: 'Turns the opening contract into a safer shield-first route.',
    detail: '+30 shield capacity and faster shield rebuilds between hits.',
    unlockVictories: 0,
    modifiers: {
      maxShieldBonus: 30,
      shieldRegenBonus: 5,
    },
  },
  {
    id: 'heat-sink',
    title: 'Synapse Heat Sink',
    slotLabel: 'Thermal stack',
    summary: 'Lets the smartguns breathe sooner and gives you a deeper energy pool.',
    detail: 'Higher heat bleed rate plus +15 max energy for rail and scatter loops.',
    unlockVictories: 0,
    modifiers: {
      heatCooldownBonus: 14,
      maxEnergyBonus: 15,
    },
  },
  {
    id: 'blink-weave',
    title: 'Blink Weave',
    slotLabel: 'Reflex lattice',
    summary: 'A mobility rig for tighter repositioning under sniper and brute pressure.',
    detail: 'Dash costs less, resets faster, and your battery recovers a little quicker.',
    unlockVictories: 1,
    modifiers: {
      dashCostMultiplier: 0.68,
      dashCooldownMultiplier: 0.72,
      energyRegenBonus: 4,
    },
  },
  {
    id: 'scrapper-daemon',
    title: 'Scrapper Daemon',
    slotLabel: 'Ghost daemon',
    summary: 'Aggressive economy kit for turning a clean extraction into long-term momentum.',
    detail: 'Improves contract payout and boosts raw credit scrap gathered in the district.',
    unlockVictories: 2,
    modifiers: {
      pickupCreditMultiplier: 0.38,
      contractPayoutBonus: 120,
    },
  },
];

export const CYBERWARE_BY_ID = Object.fromEntries(
  CYBERWARE_OPTIONS.map((option) => [option.id, option]),
) as Record<CyberwareId, CyberwareDefinition>;

export const WEAPON_UPGRADES: WeaponUpgradeDefinition[] = [
  {
    id: 'volley-overdrive',
    weapon: 'volley',
    title: 'VX Overdrive Lattice',
    slotLabel: 'Volley rifle tune',
    summary: 'Turns the VX-9 into a cleaner pressure tool with faster follow-through and tighter shield cracking.',
    detail: '-10% cycle time, +6 impact, +70 muzzle velocity, and stronger damage carry into shield fronts.',
    cost: 680,
    modifiers: {
      fireCooldownMultiplier: 0.9,
      damageBonus: 6,
      projectileSpeedBonus: 70,
      shieldBreakMultiplier: 1.18,
    },
  },
  {
    id: 'scatter-prism',
    weapon: 'scatter',
    title: 'Scatter Prism Choke',
    slotLabel: 'Scattergun tune',
    summary: 'Adds one more pellet and narrows the HX-5 spread so breach pushes feel deliberate instead of wild.',
    detail: '+1 pellet, tighter grouping, +2 impact per shard, and a slightly cheaper energy bite.',
    cost: 760,
    modifiers: {
      projectileCountBonus: 1,
      spreadMultiplier: 0.84,
      damageBonus: 2,
      energyCostMultiplier: 0.84,
    },
  },
  {
    id: 'rail-capacitor',
    weapon: 'rail',
    title: 'Rail Capacitor Spine',
    slotLabel: 'Rail lance tune',
    summary: 'Rebuilds the ARC-12 around elite deletion, with heavier punches and cleaner penetration on defended lanes.',
    detail: '+16 impact, +140 muzzle velocity, longer beam persistence, and harder shield puncture at a slightly cooler thermal load.',
    cost: 940,
    modifiers: {
      damageBonus: 16,
      projectileSpeedBonus: 140,
      projectileLifeBonus: 0.12,
      heatPerShotMultiplier: 0.9,
      shieldBreakMultiplier: 1.32,
    },
  },
];

export const WEAPON_UPGRADES_BY_ID = Object.fromEntries(
  WEAPON_UPGRADES.map((upgrade) => [upgrade.id, upgrade]),
) as Record<WeaponUpgradeId, WeaponUpgradeDefinition>;

export const CONTRACTS: ContractDefinition[] = [
  {
    id: 'morrow-relay',
    title: 'Morrow Relay Recovery',
    missionType: 'Data theft',
    client: 'Morrow Relay Co-op',
    clientFaction: 'morrow',
    hostileFaction: 'helix',
    zone: 'Vanta Stack // Relay Yard',
    districtName: 'Neon District // Vanta Stack',
    threatLabel: 'Helix retention screens',
    briefing: 'A courier uplink buried inside Vanta Stack is about to disappear under a corporate sweep. Walk the lanes, light the contract when you are ready, and get the relay back out alive.',
    routeNotes: 'Balanced intro contract with enough breathing room to learn the lane language and the first extraction rhythm.',
    unlockVictories: 0,
    basePayout: 620,
    reputationOnSuccess: 14,
    hostileHeatOnSuccess: 10,
    hostileHeatOnFailure: 4,
    startingPosition: { x: 840, y: 1160 },
    terminalPoint: { x: 560, y: 430 },
    terminalRadius: 96,
    terminalLabel: 'relay yard uplink',
    breachLabel: 'plant the courier tap',
    uploadLabel: 'data uplift',
    terminalCaptureDuration: 6,
    extractionPoint: { x: 1880, y: 360 },
    extractionRadius: 110,
    extractionLabel: 'mag-rail lift',
    extractionHoldDuration: 1.25,
    initialMission: {
      title: 'Ghost into Vanta Stack',
      detail: 'Move through the service lanes, clock the cover lines, and get ready to light the contract.',
      progress: 12,
      status: 'Recon mode',
    },
    reconSummary: 'Read the chokepoints, find the relay route, and trigger the sweep when you want live pressure.',
    objectives: [
      'Recon the relay rooftops and service corridors before the mercenary sweep starts.',
      'Plant the courier tap, hold the route long enough to finish the uplift, then cut for the lift.',
      'Extract before Helix retention teams seal the lane and turn the contract into cleanup.',
    ],
    uploadDuration: 24,
    extractionDuration: 36,
    spawnRateMultiplier: 1,
    activeCaps: {
      'reach-terminal': 6,
      'hack-terminal': 8,
      'hold-upload': 10,
      extract: 11,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'runner', 'gunner', 'shield'],
      'hack-terminal': ['runner', 'gunner', 'gunner', 'shield', 'sniper'],
      'hold-upload': ['runner', 'gunner', 'shield', 'brute', 'sniper', 'gunner'],
      extract: ['runner', 'runner', 'gunner', 'shield', 'brute', 'sniper'],
      complete: [],
    },
  },
  {
    id: 'blackout-spine',
    title: 'Blackout Spine Sabotage',
    missionType: 'Sabotage',
    client: 'Glasshouse Civic Mesh',
    clientFaction: 'glasshouse',
    hostileFaction: 'helix',
    zone: 'Tower Spine // Coolant Artery',
    districtName: 'Neon District // Tower Spine',
    threatLabel: 'Helix ordinance cell',
    briefing: 'Tower Spine is feeding Helix blackout rigs through a coolant artery that should never have gone live. Walk in quiet, arm the cascade, hold while the coil bank cooks, then vanish before the district notices what just happened.',
    routeNotes: 'Pressure-heavy sabotage route with thicker shields, more brute bodies, and a hold phase that graduates into a real elite check.',
    unlockVictories: 0,
    basePayout: 760,
    reputationOnSuccess: 16,
    hostileHeatOnSuccess: 12,
    hostileHeatOnFailure: 5,
    startingPosition: { x: 460, y: 1240 },
    terminalPoint: { x: 1120, y: 930 },
    terminalRadius: 104,
    terminalLabel: 'coil junction',
    breachLabel: 'arm the blackout cascade',
    uploadLabel: 'cascade overload',
    terminalCaptureDuration: 7.5,
    extractionPoint: { x: 1710, y: 980 },
    extractionRadius: 118,
    extractionLabel: 'coolant tram spur',
    extractionHoldDuration: 1.4,
    initialMission: {
      title: 'Slip into Tower Spine',
      detail: 'Ghost through the coolant roofs and map the service props before the sabotage goes loud.',
      progress: 10,
      status: 'Recon mode',
    },
    reconSummary: 'Tower Spine runs tighter than Vanta Stack. Learn the barricades now because the coil room turns ugly fast.',
    objectives: [
      'Work the coolant roofs and identify the safest entry into the coil junction.',
      'Arm the blackout cascade and survive the Helix purge response while the overload propagates.',
      'Break contact and leave through the tram spur before the artery gets hard-sealed.',
    ],
    uploadDuration: 28,
    extractionDuration: 33,
    spawnRateMultiplier: 1.08,
    activeCaps: {
      'reach-terminal': 7,
      'hack-terminal': 9,
      'hold-upload': 11,
      extract: 12,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'gunner', 'shield', 'shield'],
      'hack-terminal': ['gunner', 'shield', 'shield', 'sniper', 'brute'],
      'hold-upload': ['runner', 'gunner', 'shield', 'brute', 'shield', 'sniper', 'brute'],
      extract: ['runner', 'gunner', 'shield', 'brute', 'sniper'],
      complete: [],
    },
    elite: {
      phase: 'hold-upload',
      type: 'captain',
      callsign: 'Bulwark Adjunct',
      intro: 'Heavy Bulwark Adjunct inbound. Break the shield spine before it owns the coil junction.',
      bonusPayout: 190,
    },
  },
  {
    id: 'ghostline-run',
    title: 'Ghostline Witness Lift',
    missionType: 'Witness extraction',
    client: 'Morrow Relay Co-op',
    clientFaction: 'morrow',
    hostileFaction: 'glasshouse',
    zone: 'Ghostline Platforms // Market Gate',
    districtName: 'Neon District // Ghostline Market',
    threatLabel: 'Glasshouse deniable shooters',
    briefing: 'A relay witness is trying to cross Ghostline with one data shard and almost no time. You are not escorting a person in this slice, you are securing the uplink path long enough for the lift chain to form, then making the covert exit before Glasshouse overmatch takes the roof.',
    routeNotes: 'Longer cross-map route with sniper pressure and an extraction phase built around breaking one elite overwatch line.',
    unlockVictories: 1,
    basePayout: 910,
    reputationOnSuccess: 18,
    hostileHeatOnSuccess: 14,
    hostileHeatOnFailure: 6,
    startingPosition: { x: 1930, y: 1160 },
    terminalPoint: { x: 1770, y: 520 },
    terminalRadius: 100,
    terminalLabel: 'ghostline witness lock',
    breachLabel: 'stabilise the witness uplink',
    uploadLabel: 'handoff sync',
    terminalCaptureDuration: 5.5,
    extractionPoint: { x: 430, y: 1180 },
    extractionRadius: 112,
    extractionLabel: 'drainage covert exit',
    extractionHoldDuration: 1.1,
    initialMission: {
      title: 'Ghost through Market Gate',
      detail: 'Map the platform props, read the long sight lines, and prep for a fast witness lift once the district goes loud.',
      progress: 10,
      status: 'Recon mode',
    },
    reconSummary: 'This route is wider, nastier, and built around long overwatch lines. Every open lane will matter once the lift chain starts.',
    objectives: [
      'Read the market roofs and platform props before the uplink chain wakes up.',
      'Stabilise the witness lock, keep the handoff alive, and stop the deniable shooters from settling.',
      'Cross the district and hold the covert exit before Glasshouse finishes the roof.',
    ],
    uploadDuration: 22,
    extractionDuration: 30,
    spawnRateMultiplier: 1.12,
    activeCaps: {
      'reach-terminal': 7,
      'hack-terminal': 9,
      'hold-upload': 11,
      extract: 12,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'gunner', 'sniper', 'sniper'],
      'hack-terminal': ['gunner', 'sniper', 'shield', 'sniper', 'runner'],
      'hold-upload': ['runner', 'gunner', 'sniper', 'sniper', 'shield', 'brute'],
      extract: ['runner', 'gunner', 'sniper', 'sniper', 'shield'],
      complete: [],
    },
    elite: {
      phase: 'extract',
      type: 'captain',
      callsign: 'Needle Regent',
      intro: 'Needle Regent has the exit lane. Break the overwatch line or the covert drain is gone.',
      bonusPayout: 240,
    },
  },
  {
    id: 'choir-heist',
    title: 'Dead Signal Choir Heist',
    missionType: 'Broadcast heist',
    client: 'Morrow Relay Co-op',
    clientFaction: 'morrow',
    hostileFaction: 'glasshouse',
    zone: 'Choir Exchange // Signal Bridge',
    districtName: 'Neon District // Choir Exchange',
    threatLabel: 'Glasshouse witness erasers',
    briefing: 'Morrow Relay Co-op is paying you to break into Choir Exchange, pull the dead-signal ledger out of Glasshouse escrow, and escape through the choir skyhook before the witness erasers close the bridge. Cross the market lanes, crack the ghost archive if you have room, splice the dead-signal spool, hold while the ledger decompresses, then get the proof trail out before the skyline turns into a clean lie.',
    routeNotes: 'Featured authored ledger-heist slice with a real optional witness-cache branch, fixed counter-pushes, a deliberate hold rhythm, and an extraction beat that finishes on a named overwatch duel.',
    featuredLabel: 'Featured authored slice',
    unlockVictories: 0,
    basePayout: 1020,
    reputationOnSuccess: 20,
    hostileHeatOnSuccess: 15,
    hostileHeatOnFailure: 6,
    startingPosition: { x: 520, y: 1320 },
    terminalPoint: { x: 1320, y: 650 },
    terminalRadius: 108,
    terminalLabel: 'signal bridge relay',
    breachLabel: 'splice the dead-signal spool',
    uploadLabel: 'ledger decompress',
    terminalCaptureDuration: 6.4,
    extractionPoint: { x: 1880, y: 360 },
    extractionRadius: 116,
    extractionLabel: 'choir skyhook',
    extractionHoldDuration: 1.35,
    initialMission: {
      title: 'Slip into Choir Exchange',
      detail: 'Read the market props, trace the bridge approach, and get ready to pull the ledger before Glasshouse buries the witness trail.',
      progress: 10,
      status: 'Recon mode',
    },
    reconSummary: 'Choir Exchange is a shaped witness-theft route: market lane, optional archive pocket, bridge splice, hold under crossfire, then a skyhook exit before the erase teams settle.',
    objectives: [
      'Climb through the market lane and secure the signal bridge relay before Glasshouse can bury the dead-signal ledger in escrow.',
      'Optional: crack the ghost archive nest off the market lane to lift the witness cache and make the ledger undeniable.',
      'Hold the bridge while the dead-signal spool decompresses and Glasshouse counter-pushes try to retake the proof trail.',
      'Break for the choir skyhook, kill the overwatch line, and get the ledger out before the skyline closes on you.',
    ],
    uploadDuration: 24,
    extractionDuration: 28,
    spawnRateMultiplier: 0.98,
    activeCaps: {
      'reach-terminal': 6,
      'hack-terminal': 7,
      'hold-upload': 9,
      extract: 10,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'gunner', 'shield'],
      'hack-terminal': ['gunner', 'shield', 'sniper'],
      'hold-upload': ['runner', 'gunner', 'shield', 'brute'],
      extract: ['runner', 'gunner', 'shield', 'sniper'],
      complete: [],
    },
    elite: {
      phase: 'extract',
      type: 'captain',
      callsign: 'Velvet Knife',
      intro: 'Velvet Knife just took the skyhook lane. Break the captain or the whole exit closes under overwatch.',
      bonusPayout: 260,
    },
    optionalObjective: {
      id: 'ghost-archive',
      title: 'Ghost archive nest',
      shortLabel: 'Ghost archive',
      detail: 'Slip into the side archive pocket and ghost the witness cache before you hit the bridge. It costs time and wakes a local erase team, but if you still extract the ledger becomes proof instead of just theft.',
      summary: 'Crack the ghost archive pocket for the witness cache before you commit to the bridge.',
      rewardLabel: '+180c payout // +4 Morrow rep if extracted',
      position: { x: 980, y: 900 },
      radius: 92,
      captureDuration: 4.8,
      availablePhases: ['reach-terminal'],
      bonusCredits: 180,
      reputationBonus: 4,
      completionStatus: 'Ghost archive cracked',
      completionSummary: 'You lifted the witness cache before the bridge went loud. Now the ledger can name the deal and the archive can prove who got buried to close it.',
      skipStatus: 'Ghost archive abandoned',
      skipSummary: 'You left the archive dark to keep tempo on the bridge. The contract still closes, but the cleanest witness trail stayed under Glasshouse lock.',
      ambushSpawns: [
        { type: 'runner', position: { x: 1120, y: 980 } },
        { type: 'gunner', position: { x: 1180, y: 900 } },
        { type: 'shield', position: { x: 1040, y: 760 } },
      ],
    },
    authoredBeats: [
      {
        id: 'arcade-tripwire',
        phase: 'reach-terminal',
        trigger: { kind: 'phase-elapsed', seconds: 1.2 },
        status: 'Arcade tripwire sprung',
        summary: 'Glasshouse spotters broke cover in the market lane. Clean the first screen, then keep climbing toward the bridge.',
        spawns: [
          { type: 'runner', position: { x: 760, y: 1260 } },
          { type: 'runner', position: { x: 940, y: 1170 } },
          { type: 'gunner', position: { x: 1180, y: 980 } },
        ],
      },
      {
        id: 'bridge-lock',
        phase: 'hack-terminal',
        trigger: { kind: 'phase-start' },
        status: 'Bridge shutters dropping',
        summary: 'The splice woke the bridge. Shield crews are pinching from both stair mouths, so hold the ring and break the push in halves.',
        spawns: [
          { type: 'shield', position: { x: 1180, y: 790 } },
          { type: 'gunner', position: { x: 1460, y: 760 } },
          { type: 'shield', position: { x: 1320, y: 520 } },
        ],
      },
      {
        id: 'awning-overwatch',
        phase: 'hold-upload',
        trigger: { kind: 'phase-elapsed', seconds: 7.5 },
        status: 'Exchange awnings occupied',
        summary: 'Glasshouse settled the awnings and pushed a brute up the main ramp. Rotate cover now or the bridge turns into a firing gallery.',
        spawns: [
          { type: 'sniper', position: { x: 1690, y: 520 } },
          { type: 'sniper', position: { x: 1770, y: 340 } },
          { type: 'brute', position: { x: 1160, y: 1030 } },
        ],
      },
      {
        id: 'skyhook-scramble',
        phase: 'extract',
        trigger: { kind: 'phase-start' },
        status: 'Skyhook corridor open',
        summary: 'The ledger is free. Burn for the choir skyhook before the erase teams fold the lane behind you.',
        spawns: [
          { type: 'runner', position: { x: 1540, y: 700 } },
          { type: 'shield', position: { x: 1670, y: 590 } },
          { type: 'gunner', position: { x: 1820, y: 470 } },
        ],
      },
      {
        id: 'rear-cutoff',
        phase: 'extract',
        trigger: { kind: 'phase-elapsed', seconds: 8.5 },
        status: 'Rear screen collapsing',
        summary: 'Rear pressure is folding in. Do not chase the scraps; hold the skyhook ring and let the district break around you.',
        spawns: [
          { type: 'brute', position: { x: 1080, y: 860 } },
          { type: 'gunner', position: { x: 1280, y: 680 } },
          { type: 'runner', position: { x: 930, y: 720 } },
        ],
      },
    ],
    victorySummary: 'The dead-signal spool cracked, the skyhook took the ledger, and Glasshouse lost the bridge receipt before the erase teams could turn Choir Exchange quiet again.',
    failureSummary: 'The skyhook window died under Glasshouse overwatch, the ledger went back into escrow, and the bridge stayed bought for another night.',
  },
  {
    id: 'glassfall-siege',
    title: 'Glassfall Nullbreaker Siege',
    missionType: 'Fortress break',
    client: 'Glasshouse Civic Mesh',
    clientFaction: 'glasshouse',
    hostileFaction: 'helix',
    zone: 'Glassfall Verge // Shard Vault',
    districtName: 'Neon District // Glassfall Verge',
    threatLabel: 'Helix siege cadre',
    briefing: 'Helix rolled a nullbreaker engine into Glassfall Verge and started hard-sealing the block around a shard vault nobody can afford to lose. Cut through the verge, overclock the vault crown until the engine exposes its command spine, then hold long enough to break the siege captain and steal a flood-tram exit before the whole lane collapses.',
    routeNotes: 'Boss-grade authored contract with a heavier central hold, a named siege captain in the kill box, and an extraction that pays off like a real mission finish.',
    featuredLabel: 'Boss-grade slice',
    unlockVictories: 2,
    basePayout: 1320,
    reputationOnSuccess: 22,
    hostileHeatOnSuccess: 18,
    hostileHeatOnFailure: 8,
    startingPosition: { x: 1980, y: 1290 },
    terminalPoint: { x: 1120, y: 930 },
    terminalRadius: 114,
    terminalLabel: 'shard vault crown',
    breachLabel: 'overclock the nullbreaker beacons',
    uploadLabel: 'crown overload',
    terminalCaptureDuration: 6.8,
    extractionPoint: { x: 360, y: 820 },
    extractionRadius: 124,
    extractionLabel: 'flood-tram breach',
    extractionHoldDuration: 1.55,
    initialMission: {
      title: 'Cut into Glassfall Verge',
      detail: 'Map the barricades, clock the catwalk sight lines, and get ready for a louder contract than Choir Exchange.',
      progress: 9,
      status: 'Recon mode',
    },
    reconSummary: 'Glassfall is a siege route. The props are denser, the shield bodies hit earlier, and the vault crown is designed to pull a captain into the center of the map.',
    objectives: [
      'Work through Glassfall Verge and reach the shard vault crown before Helix hard-seals the block.',
      'Hold the vault while the crown overload drags the siege cadre into a boss-grade counterpush.',
      'Break for the flood-tram breach and extract before the nullbreaker closes the lane behind you.',
    ],
    uploadDuration: 30,
    extractionDuration: 32,
    spawnRateMultiplier: 1.12,
    activeCaps: {
      'reach-terminal': 7,
      'hack-terminal': 9,
      'hold-upload': 11,
      extract: 12,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'gunner', 'shield', 'sniper'],
      'hack-terminal': ['gunner', 'shield', 'shield', 'brute', 'sniper'],
      'hold-upload': ['runner', 'gunner', 'shield', 'brute', 'sniper', 'shield', 'brute'],
      extract: ['runner', 'gunner', 'shield', 'brute', 'sniper', 'shield'],
      complete: [],
    },
    elite: {
      phase: 'hold-upload',
      type: 'captain',
      callsign: 'Cinder Bishop',
      intro: 'Cinder Bishop is on the vault floor with the nullbreaker spine. Break the captain or the overload dies in the box.',
      bonusPayout: 320,
    },
    authoredBeats: [
      {
        id: 'verge-screen',
        phase: 'reach-terminal',
        trigger: { kind: 'phase-start' },
        status: 'Verge screen broken',
        summary: 'Helix sent a first contact screen across the verge. Kill the opening bodies fast and keep the vault crown in front of you.',
        spawns: [
          { type: 'runner', position: { x: 1800, y: 1200 } },
          { type: 'shield', position: { x: 1650, y: 1110 } },
          { type: 'gunner', position: { x: 1490, y: 1020 } },
        ],
      },
      {
        id: 'catwalk-sutures',
        phase: 'reach-terminal',
        trigger: { kind: 'phase-elapsed', seconds: 3.2 },
        status: 'Catwalks stitched shut',
        summary: 'Snipers just took the catwalk seams. You have enough props to work the lane, but not enough to drift in the open.',
        spawns: [
          { type: 'sniper', position: { x: 1710, y: 540 } },
          { type: 'sniper', position: { x: 1540, y: 450 } },
          { type: 'gunner', position: { x: 1410, y: 690 } },
        ],
      },
      {
        id: 'vault-bolt',
        phase: 'hack-terminal',
        trigger: { kind: 'phase-start' },
        status: 'Vault shutters locking',
        summary: 'The crown woke the whole vault. Shield crews are pinching both doors, and a brute is already trying to stand on the ring.',
        spawns: [
          { type: 'shield', position: { x: 960, y: 1015 } },
          { type: 'shield', position: { x: 1270, y: 820 } },
          { type: 'brute', position: { x: 1100, y: 1170 } },
          { type: 'gunner', position: { x: 1350, y: 980 } },
        ],
      },
      {
        id: 'beacon-shear',
        phase: 'hold-upload',
        trigger: { kind: 'phase-start' },
        status: 'Nullbreaker beacons flaring',
        summary: 'The overload is live. The center is now a kill box, so rotate hard cover and keep the crown from turning into a grave.',
        spawns: [
          { type: 'runner', position: { x: 880, y: 1110 } },
          { type: 'shield', position: { x: 940, y: 760 } },
          { type: 'brute', position: { x: 1320, y: 1110 } },
        ],
      },
      {
        id: 'siege-collapse',
        phase: 'hold-upload',
        trigger: { kind: 'phase-elapsed', seconds: 8.8 },
        status: 'Siege lattice collapsing inward',
        summary: 'The nullbreaker is throwing everything left into the vault. Finish the captain and clear a route now, because the exit beat starts the moment the crown breaks.',
        spawns: [
          { type: 'sniper', position: { x: 1500, y: 660 } },
          { type: 'gunner', position: { x: 760, y: 870 } },
          { type: 'shield', position: { x: 1280, y: 680 } },
        ],
      },
      {
        id: 'tram-breach',
        phase: 'extract',
        trigger: { kind: 'phase-start' },
        status: 'Flood-tram breach open',
        summary: 'The crown snapped the siege line. Burn for the flood tram before Helix reseals the verge behind the vault.',
        spawns: [
          { type: 'runner', position: { x: 860, y: 930 } },
          { type: 'shield', position: { x: 690, y: 870 } },
          { type: 'gunner', position: { x: 520, y: 790 } },
        ],
      },
      {
        id: 'tram-last-stand',
        phase: 'extract',
        trigger: { kind: 'phase-elapsed', seconds: 7.4 },
        status: 'Rear pursuit at the tram lip',
        summary: 'Helix is throwing the last bodies straight at the breach. Hold the ring, do not chase the tail, and leave the district with the vault still burning.',
        spawns: [
          { type: 'brute', position: { x: 980, y: 920 } },
          { type: 'shield', position: { x: 760, y: 760 } },
          { type: 'sniper', position: { x: 540, y: 600 } },
        ],
      },
    ],
    victorySummary: 'The shard vault crown burned through the nullbreaker spine, Cinder Bishop died in the box, and the flood tram carried Glassfall out from under Helix siege lights.',
    failureSummary: 'Glassfall sealed around the nullbreaker, the flood-tram breach died under Helix pressure, and the shard vault went dark behind you.',
  },
  {
    id: 'redline-blackout',
    title: 'Redline Blackout Run',
    missionType: 'Blackout survival',
    client: 'Morrow Relay Co-op',
    clientFaction: 'morrow',
    hostileFaction: 'helix',
    zone: 'Transit Coil // Blackout Spillway',
    districtName: 'Neon District // Transit Coil',
    threatLabel: 'Helix blackout wardens',
    briefing: 'Transit Coil is trying to reboot after a district blackout, and Helix just turned the restart grid into a kill switch. Push to the spillway control tower, stabilise the relays while the floor throws live surge blooms, then ride the maintenance magline out before the whole coil arcs itself back into darkness.',
    routeNotes: 'Hazard-driven authored slice built around timed shock blooms, safer movement windows, and a survival rhythm that reads differently from the boss or showcase lanes.',
    featuredLabel: 'Hazard slice',
    unlockVictories: 2,
    basePayout: 1180,
    reputationOnSuccess: 19,
    hostileHeatOnSuccess: 16,
    hostileHeatOnFailure: 7,
    startingPosition: { x: 340, y: 1340 },
    terminalPoint: { x: 920, y: 980 },
    terminalRadius: 112,
    terminalLabel: 'spillway control tower',
    breachLabel: 'stabilise the blackout relays',
    uploadLabel: 'grid restart',
    terminalCaptureDuration: 6.2,
    extractionPoint: { x: 1920, y: 500 },
    extractionRadius: 118,
    extractionLabel: 'maintenance magline',
    extractionHoldDuration: 1.28,
    initialMission: {
      title: 'Ghost into Transit Coil',
      detail: 'Map the barricades and catwalk seams before the blackout wards go live.',
      progress: 10,
      status: 'Recon mode',
    },
    reconSummary: 'Transit Coil is a timing route. The props still matter, but the real test is reading when the floor is safe enough to cross.',
    objectives: [
      'Reach the spillway control tower and stabilise the blackout relays before Helix hard-seals the coil.',
      'Hold through the restart while timed surge blooms force you to move on rhythm instead of camping the ring.',
      'Burn to the maintenance magline and extract through the last blackout pulses before the district goes dark again.',
    ],
    uploadDuration: 27,
    extractionDuration: 34,
    spawnRateMultiplier: 1.04,
    activeCaps: {
      'reach-terminal': 6,
      'hack-terminal': 8,
      'hold-upload': 10,
      extract: 10,
    },
    enemyPacks: {
      recon: [],
      'reach-terminal': ['runner', 'gunner', 'shield'],
      'hack-terminal': ['gunner', 'shield', 'sniper', 'runner'],
      'hold-upload': ['runner', 'gunner', 'shield', 'brute', 'sniper'],
      extract: ['runner', 'gunner', 'shield', 'sniper'],
      complete: [],
    },
    authoredBeats: [
      {
        id: 'spillway-screen',
        phase: 'reach-terminal',
        trigger: { kind: 'phase-start' },
        status: 'Spillway screen active',
        summary: 'Helix lifted the first blackout wardens onto the spillway. Clear the opening bodies and keep the control tower in sight.',
        spawns: [
          { type: 'runner', position: { x: 520, y: 1240 } },
          { type: 'gunner', position: { x: 690, y: 1140 } },
          { type: 'shield', position: { x: 820, y: 1050 } },
        ],
      },
      {
        id: 'coil-lock',
        phase: 'hack-terminal',
        trigger: { kind: 'phase-start' },
        status: 'Coil shutters locking',
        summary: 'The tower woke the whole spillway. Hold the ring while Helix tries to box you in from the lower ramps.',
        spawns: [
          { type: 'shield', position: { x: 780, y: 1090 } },
          { type: 'gunner', position: { x: 1110, y: 880 } },
          { type: 'sniper', position: { x: 1270, y: 680 } },
        ],
      },
      {
        id: 'wardens-advance',
        phase: 'hold-upload',
        trigger: { kind: 'phase-elapsed', seconds: 6.8 },
        status: 'Blackout wardens surging',
        summary: 'The restart is loud now. Helix is advancing through the safe pockets, so use the blooms to break their tempo before they break yours.',
        spawns: [
          { type: 'runner', position: { x: 730, y: 900 } },
          { type: 'brute', position: { x: 1110, y: 1160 } },
          { type: 'gunner', position: { x: 1380, y: 820 } },
        ],
      },
      {
        id: 'magline-dive',
        phase: 'extract',
        trigger: { kind: 'phase-start' },
        status: 'Magline breach open',
        summary: 'The relays held. Sprint the magline while the last wardens try to own the only clean lane out of Transit Coil.',
        spawns: [
          { type: 'runner', position: { x: 1320, y: 820 } },
          { type: 'shield', position: { x: 1520, y: 670 } },
          { type: 'sniper', position: { x: 1730, y: 520 } },
        ],
      },
    ],
    hazards: [
      {
        id: 'relay-flare',
        phase: 'hack-terminal',
        trigger: { kind: 'phase-start' },
        kind: 'shock',
        label: 'Relay flare',
        status: 'Relay flare live',
        summary: 'Shock arcs are snapping across the control ring. Dip in, stabilise, then break out before the flare cooks the floor.',
        position: { x: 940, y: 980 },
        radius: 132,
        duration: 7.2,
        damagePerSecond: 14,
        color: '#4cefff',
      },
      {
        id: 'spillway-bloom',
        phase: 'hold-upload',
        trigger: { kind: 'phase-elapsed', seconds: 4.5 },
        kind: 'blackout',
        label: 'Blackout bloom',
        status: 'Blackout bloom expanding',
        summary: 'The spillway floor is dropping into a dead zone. Move on rhythm and use the safe pockets instead of trying to tank the bloom.',
        position: { x: 1140, y: 900 },
        radius: 180,
        duration: 8.4,
        damagePerSecond: 16,
        color: '#7f7cff',
      },
      {
        id: 'backwash-arc',
        phase: 'hold-upload',
        trigger: { kind: 'phase-elapsed', seconds: 13.4 },
        kind: 'shock',
        label: 'Backwash arc',
        status: 'Backwash arc rolling',
        summary: 'The restart kicked a second wave back through the lower spillway. Shift positions now or the floor will pin you in place for Helix.',
        position: { x: 860, y: 1140 },
        radius: 150,
        duration: 7.6,
        damagePerSecond: 15,
        color: '#ff8fd9',
      },
      {
        id: 'magline-surge',
        phase: 'extract',
        trigger: { kind: 'phase-start' },
        kind: 'blackout',
        label: 'Magline surge',
        status: 'Magline surge active',
        summary: 'The exfil lane is blinking in and out under surge pressure. Move when the field opens and do not stall inside the bloom.',
        position: { x: 1680, y: 610 },
        radius: 170,
        duration: 9.5,
        damagePerSecond: 15,
        color: '#ffc45f',
      },
    ],
    victorySummary: 'The relays came back online, Transit Coil stayed lit long enough for the magline to take you out, and Helix lost the blackout lane.',
    failureSummary: 'The blackout fields swallowed Transit Coil, the magline blinked out, and Helix left the district in the dark again.',
  },
];

export const CONTRACTS_BY_ID = Object.fromEntries(
  CONTRACTS.map((contract) => [contract.id, contract]),
) as Record<ContractId, ContractDefinition>;
